language: csharp

mono: 4.6.2

dotnet: 2.2.402
 
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet : 2.1.300
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet : 2.1.300
      dist: trusty
      sudo: required

script: 
  - ./fake.sh build target all

branches:
  except:
    - gh-pages
